# Generated by Django 3.2.7 on 2021-09-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='Shop_produc_id_451ad9_idx',
        ),
    ]
