# Generated by Django 3.2.7 on 2021-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_product_shop_produc_id_451ad9_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='Shop_produc_id_451ad9_idx'),
        ),
    ]
